namespace LinuxDbus.Bluetooth.BlueZ;

// <auto-generated Note="Disabled CodeMaid's auto-sorting" />
/// <summary>https://www.bluetooth.com/specifications/gatt/</summary>
public class GattUuid
{
  // Device Information
  public const string DeviceInformationService = "0000180a-0000-1000-8000-00805f9b34fb";
  public const string ModelNameCharacteristic = "00002a24-0000-1000-8000-00805f9b34fb";
  public const string ManufacturerNameCharacteristic = "00002a29-0000-1000-8000-00805f9b34fb";

  // Current Time
  public const string CurrentTimeService = "00001805-0000-1000-8000-00805f9b34fb";
  public const string CurrentTimeCharacteristic = "00002a2b-0000-1000-8000-00805f9b34fb";

  // Battery Service
  // BlueZ presents this service a separate interface, Battery1.
  // public const string BatteryService = "0000180f-0000-1000-8000-00805f9b34fb";
  // public const string BatteryLevelCharacteristic = "00002a19-0000-1000-8000-00805f9b34fb";

  // Apple Notification Center Service (ANCS)
  // https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/AppleNotificationCenterServiceSpecification/Introduction/Introduction.html
  public const string ANCService = "7905f431-b5ce-4e99-a40f-4b1e122d00d0";

  // TODO: Lowercase these.
  public const string ANCSNotificationSource = "9FBF120D-6301-42D9-8C58-25E699A21DBD";
  public const string ANCSControlPoint = "69D1D8F3-45E1-49A8-9821-9BBDFDAAD9D9";
  public const string ANCSDataSource = "22EAC6E9-24D6-4BB5-BE44-B36ACE7C7BFB";
}
